config/routes.rb
Rails.application.routes.draw do
  root      'pages#samdhya'
  resources :pages, except: [:show]
  get       '/:id', to: 'pages#show', as: :show_page
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :slug,  presence: true, uniqueness: true,
                    length: { maximum: 80 },
                    format: { with: /\A([a-z]|\d|-)+\z/ },
                    exclusion: { in: %w(pages) }

  before_validation :create_slug, if: -> (page) { page.slug.blank? }

  def to_param
    slug
  end

  private

  def create_slug
    self.slug = title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name:     ENV['ADMIN_EMAIL'],
                               password: ENV['ADMIN_PASSWORD'],
                               except:   [:samdhya, :show]

  before_action :set_page, only: [:show, :edit, :update]

  def samdhya
    @page = Page.find_by(slug: 'samdhya')
    render 'show'
  end

  def show
  end

  def index
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(permitted_params)
    if @page.save
      redirect_to show_page_url @page
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @page.update_attributes(permitted_params)
      redirect_to show_page_url @page
    else
      render 'edit'
    end
  end

  private

  def permitted_params
    params.require(:page).permit(:title, :content)
  end

  def set_page
    @page = Page.find_by(slug: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Samdhya
    meta content='width=device-width, initial-scale=1.0' name='viewport'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container-fluid
      .row
        .col-xs-10.col-xs-offset-1.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
          .header
            .col-xs-4
              h1.brand Ceri
            .col-xs-8
              = render 'shared/navbar'
      .row
        .col-xs-10.col-xs-offset-1.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
          = yield

app/views/pages/_page_form_fields.html.slim
= f.input :title
= f.input :slug
= f.input :content, input_html: { rows: 10 }

app/views/pages/edit.html.slim
= simple_form_for @page do |f|
  == render 'page_form_fields', f: f
  = f.button :submit, class: 'btn-primary'

app/views/pages/index.html.slim
.page
  h1.page-title Page index
  .page-content
    p This is the index page. It should contain some welcome information and a brief introduction to the main pages Ceri wants to attract the visitor to.

app/views/pages/new.html.slim
= simple_form_for @page do |f|
  = render 'page_form_fields', f: f
  = f.button :submit, class: 'btn-primary'

app/views/pages/show.html.slim
.page
  h1.page-title= @page.title
  .page-content
    = simple_format @page.content

app/views/shared/_navbar.html.slim
nav.nav role='navigation'
  ul.nav.nav-pills
    - nav_order = %w(Samdhya Ceri Stars Flowers Food)
    - pages = nav_order.map { |title| Page.find_by(title: title) }
    - for page in pages
      li= link_to page.title, show_page_path(page) if page